#define Matrix3F_mulva_sse2 Matrix3F_mulva_scalar
#define Matrix3F_mulv_sse2 Matrix3F_mulv_scalar
#define Matrix3F_mul_sse2 Matrix3F_mul_scalar

#define Matrix4F_mulva_sse2 Matrix4F_mulva_scalar
#define Matrix4F_mulv_sse2 Matrix4F_mulv_scalar
#define Matrix4F_mult_sse2 Matrix4F_mult_scalar
#define Matrix4F_mul_sse2 Matrix4F_mul_scalar
