typedef enum {
	PARSER_KEYWORD_RETURN,
	PARSER_KEYWORD_THROW,
	PARSER_KEYWORD_BREAK,
	PARSER_KEYWORD_CONTINUE,
	PARSER_KEYWORD_EMIT,
	PARSER_KEYWORD_JUMP,
	PARSER_KEYWORD_EXIT,
	PARSER_KEYWORD_IF,
	PARSER_KEYWORD_ELSE,
	PARSER_KEYWORD_LOOP,
	PARSER_KEYWORD_CATCH,
	PARSER_KEYWORD_PRINT,
	PARSER_KEYWORD_SET,
	PARSER_KEYWORD_SET_PTR,
	PARSER_KEYWORD_GET_PTR,
	PARSER_KEYWORD_TAKE_PTR,
	PARSER_KEYWORD_PTR
} EParserKeyword;
