typedef enum {
	TOKEN_TYPE_IDENTIFIER,
	TOKEN_TYPE_NUMERIC_LITERAL,
	TOKEN_TYPE_STRING_LITERAL,
	TOKEN_TYPE_LIST_DELIMITER,
	TOKEN_TYPE_BRACE_OPEN,
	TOKEN_TYPE_BRACE_CLOSE,
	TOKEN_TYPE_SBRACE_OPEN,
	TOKEN_TYPE_SBRACE_CLOSE,
	TOKEN_TYPE_CBRACE_OPEN,
	TOKEN_TYPE_CBRACE_CLOSE,
	TOKEN_TYPE_IMPLICIT_END,
	TOKEN_TYPE_END,
	TOKEN_TYPE_ACCESSOR,
	TOKEN_TYPE_INPUT_END,
	TOKEN_TYPE__END
} ETokenType;

const char *ETokenType_repr[TOKEN_TYPE__END] = {
	[TOKEN_TYPE_IDENTIFIER] = "TOKEN_TYPE_IDENTIFIER",	
	[TOKEN_TYPE_NUMERIC_LITERAL] = "TOKEN_TYPE_NUMERIC_LITERAL",	
	[TOKEN_TYPE_STRING_LITERAL] = "TOKEN_TYPE_STRING_LITERAL",	
	[TOKEN_TYPE_LIST_DELIMITER] = "TOKEN_TYPE_LIST_DELIMITER",
	[TOKEN_TYPE_BRACE_OPEN] = "TOKEN_TYPE_BRACE_OPEN",
	[TOKEN_TYPE_BRACE_CLOSE] = "TOKEN_TYPE_BRACE_CLOSE",
	[TOKEN_TYPE_SBRACE_OPEN] = "TOKEN_TYPE_SBRACE_OPEN",
	[TOKEN_TYPE_SBRACE_CLOSE] = "TOKEN_TYPE_SBRACE_CLOSE",
	[TOKEN_TYPE_CBRACE_OPEN] = "TOKEN_TYPE_CBRACE_OPEN",
	[TOKEN_TYPE_CBRACE_CLOSE] = "TOKEN_TYPE_CBRACE_CLOSE",
	[TOKEN_TYPE_IMPLICIT_END] = "TOKEN_TYPE_IMPLICIT_END",
	[TOKEN_TYPE_END] = "TOKEN_TYPE_END",
	[TOKEN_TYPE_INPUT_END] = "TOKEN_TYPE_INPUT_END"
};
