#include "typing/Type.c"
#include "typing/Qualifier.c"

#include "tree/Identifier.c"
#include "tree/Member.c"

#include "sim/config.h"
#include "sim/SimCache.h"
#include "sim/SimStackFrame.h"
#include "sim/SimContext.h"
#include "sim/SimValue.h"
#include "sim/SimResult.h"
#include "sim/SimNode.h"

#include "tree/Node.c"

#include "typing/types/Primitive.c"
#include "typing/types/Pointer.c"
#include "typing/types/Qualifier.c"
#include "typing/types/Function.c"
#include "typing/types/Union.c"
#include "typing/types/Tuple.c"
#include "typing/types/Array.c"

#include "tree/Function.c"

#include "tree/nodes/Frame.c"
#include "tree/nodes/Sequence.c"
#include "tree/nodes/Get.c"
#include "tree/nodes/Set.c"
#include "tree/nodes/Cast.c"
#include "tree/nodes/Condition.c"
#include "tree/nodes/Value.c"
#include "tree/nodes/Builtin.c"
#include "tree/nodes/Control.c"
#include "tree/nodes/GetPointer.c"
#include "tree/nodes/SetPointer.c"
#include "tree/nodes/TakePointer.c"
#include "tree/nodes/Catch.c"
#include "tree/nodes/Call.c"


#include "typing/qualifiers/Primitive.c"
#include "typing/qualifiers/Union.c"


#include "sim/SimCache.c"
#include "sim/SimStackFrame.c"
#include "sim/SimContext.c"
#include "sim/SimValue.c"
#include "sim/SimResult.c"
#include "sim/SimNode.c"

#include "sim/impl/Get.c"
#include "sim/impl/Set.c"
#include "sim/impl/Cast.c"
#include "sim/impl/Sequence.c"
#include "sim/impl/Frame.c"
#include "sim/impl/Value.c"
#include "sim/impl/Condition.c"
#include "sim/impl/Builtin.c"
#include "sim/impl/Control.c"
#include "sim/impl/GetPointer.c"
#include "sim/impl/SetPointer.c"
#include "sim/impl/TakePointer.c"
#include "sim/impl/Catch.c"
#include "sim/impl/Call.c"
